export default [
    "Java",
    "JavaScript",
    "C++",
    "Python",
    "C#",
    "PHP",
    "Typescript",
    "ReactJS",
    "NodeJS",
    // "Kotlin",
    "Android Development",
    "GIT",
    "MySQL / PostgreSQL",
    "Laravel",
    "Jira",
    "Trello",
    "UX / Responsive Design",
    "Agile Development (SCRUM)",
    "CSS",
    "SASS",
    "Unit Testing (TestNG, JUnit & Jest)",
    "Gradle",
    "Jquery",
    "Niagara Framework",
    "RequireJS",
    "Webpack",
    "Babel",
    "AJAX",
    // "Apache HTTP Server",
    "Linux CLI",
    "..."
]