export default [
    "JavaScript",
    "Typescript",
    "ReactJS",
    "NodeJS",
    "Java",
    "Kotlin",
    "Android Development",
    "GIT",
    "MySQL / PostgreSQL",
    "C#",
    "ASP.net",
    "Jira & Trello",
    "PHP",
    "Laravel",
    "Python",
    "UX / Responsive Design",
    "Agile Development (SCRUM)",
    "CSS",
    "SASS",
    "Unit Testing (TestNG & Jest)",
    "Gradle",
    "Jquery",
    "Niagara Framework",
    "RequireJS",
    "Webpack",
    "Babel",
    "AJAX",
    "Apache",
    "BASH"
]